/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-26 07:25:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.intro;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class section_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/F:/teamProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/teampro01/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1716518186449L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1716518186542L));
    _jspx_dependants.put("jar:file:/F:/teamProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/teampro01/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/F:/teamProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/teampro01/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1716518186621L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1716518209898L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /intro/section.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("path0");
        // /intro/section.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(request.getContextPath() );
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f1_reused = false;
      try {
        _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f1.setParent(null);
        // /head.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setVar("ipath");
        // /head.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setValue(request.getContextPath() );
        int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
        if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        _jspx_th_c_005fset_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
      }
      out.write("    \r\n");
      out.write("<!--  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.2.1.min.js\"></script>-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" />\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"subject\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("<meta property=\"og:type\" content=\"website\" />\r\n");
      out.write("<meta property=\"og:description\" content=\"\" />\r\n");
      out.write("<meta property=\"og:image\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("<meta property=\"og:url\" content=\"http://localhost:8091\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/fonts.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/normalize2.css\">\r\n");
      out.write("<meta name=\"subject\" content=\"강화 소개(GangHwa Intro)\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"강화, 맛집, 숙박, 쇼핑, 체험, 명소, 전시관, 박물관, 여행, 축제\" />\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/favicon.png\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/favicon.png\" />\r\n");
      out.write("<meta property=\"og:title\" content=\"gangHwa\" />\r\n");
      out.write("<meta property=\"og:description\" content=\"강화, 맛집, 숙박, 쇼핑, 체험, 명소, 전시관, 박물관, 여행, 축제\" />");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    #contents { height: 1300px; }\r\n");
      out.write("    .wrap .box li { margin-top:30px; margin-left: 70px; float: left; width: 302px; height: 302px; \r\n");
      out.write("    border: 1px solid #000; position: relative; }\r\n");
      out.write("    .wrap .box li:hover #cover { display: block; cursor: pointer; }\r\n");
      out.write("\r\n");
      out.write("    .box .text { z-index: 10; position: absolute; width: 300px; height: 50px; line-height: 50px; text-align: center; \r\n");
      out.write("    font-weight: bold; font-size: 17px; background-color: #eccfe9; }\r\n");
      out.write("\r\n");
      out.write("    #img { width: 300px; height: 300px; position: absolute; z-index: 10; }\r\n");
      out.write("    #cover { width: 300px; height: 300px; position: absolute; display: none; z-index: 11; }\r\n");
      out.write("</style>\r\n");
      out.write("<title>일반현황/행정구역</title>\r\n");
      out.write("<style>\r\n");
      out.write("#contents { height: 1300px; }\r\n");
      out.write(".wrap .box li { margin-top:30px; margin-left: 70px; float: left; width: 300px; height: 300px; \r\n");
      out.write("border: 1px solid #000; position: relative; }\r\n");
      out.write(".wrap .box li:hover #cover { display: block; cursor: pointer; }\r\n");
      out.write("\r\n");
      out.write(".box .text { z-index: 10; position: absolute; width: 300px; height: 50px; line-height: 50px; text-align: center; \r\n");
      out.write("font-weight: bold; font-size: 17px; background-color: #eccfe9; }\r\n");
      out.write("\r\n");
      out.write("#img { width: 300px; height: 300px; position: absolute; z-index: 10; }\r\n");
      out.write("#cover { width: 300px; height: 300px; position: absolute; display: none; z-index: 11; }\r\n");
      out.write("\r\n");
      out.write(".title2 { display: flex; margin-left: 70px; margin-top: 40px; }\r\n");
      out.write("#title_img { width: 30px; height: 30px; }\r\n");
      out.write(".sub_title { width: 400px; margin-left: 10px; padding-top: 5px; }\r\n");
      out.write("\r\n");
      out.write("h3 { margin-left: 70px; margin-top: 40px; }\r\n");
      out.write(".box_img { display: flex; }\r\n");
      out.write("#intro_img1 { display: flex; width: 80%; height: auto; margin: 0 auto; margin-top: 30px; }\r\n");
      out.write("#intro_img2 { display: flex; width: 500px; height: 400px; margin-left: 70px; margin-right: 70px; margin-top: 40px; \r\n");
      out.write("border:2px solid #000; }\r\n");
      out.write("\r\n");
      out.write(".intro { margin-left: 70px; margin-top: 40px; margin-right: 70px; height: 200px; }\r\n");
      out.write("\r\n");
      out.write("table { width: 88%; border-collapse: collapse; margin-left: 70px; margin-right: 70px; }\r\n");
      out.write("th { background-color: pink; }\r\n");
      out.write("th, td { border: 2px solid #000; padding: 8px; text-align: center; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 탭 */\r\n");
      out.write(".tab_con { display:none; position:absolute; top:48px; left: 0; }\r\n");
      out.write(".tab_ra { display:none; }\r\n");
      out.write(".tab_ra:checked ~ .tab_con { display:block; }\r\n");
      out.write("\r\n");
      out.write(".ra_item { display:none; }\r\n");
      out.write(".tab_con_box { display:none; }\r\n");
      out.write("#ra1:checked ~ .tab_con_wrap #tab_con_box1 { display:block; }\r\n");
      out.write("#ra2:checked ~ .tab_con_wrap #tab_con_box2 { display:block; }\r\n");
      out.write("#ra3:checked ~ .tab_con_wrap #tab_con_box3 { display:block; }\r\n");
      out.write("#ra4:checked ~ .tab_con_wrap #tab_con_box4 { display:block; }\r\n");
      out.write("#ra5:checked ~ .tab_con_wrap #tab_con_box5 { display:block; }\r\n");
      out.write("#ra6:checked ~ .tab_con_wrap #tab_con_box6 { display:block; }\r\n");
      out.write("#ra7:checked ~ .tab_con_wrap #tab_con_box7 { display:block; }\r\n");
      out.write("#ra8:checked ~ .tab_con_wrap #tab_con_box8 { display:block; }\r\n");
      out.write("#ra9:checked ~ .tab_con_wrap #tab_con_box9 { display:block; }\r\n");
      out.write("#ra10:checked ~ .tab_con_wrap #tab_con_box10 { display:block; }\r\n");
      out.write("#ra11:checked ~ .tab_con_wrap #tab_con_box11 { display:block; }\r\n");
      out.write("#ra12:checked ~ .tab_con_wrap #tab_con_box12 { display:block; }\r\n");
      out.write("#ra13:checked ~ .tab_con_wrap #tab_con_box13 { display:block; }\r\n");
      out.write("\r\n");
      out.write("#tab2 { width: 1200px; height: 350px; clear:both; }\r\n");
      out.write(".tb_wrap { width: 1200px; margin-top: 50px; margin: 40px auto; display: flex; }\r\n");
      out.write("\r\n");
      out.write(".btn_box { width: 500px; margin-bottom: 45px; margin-left: 70px; }\r\n");
      out.write(".btn_box .ra_btn { display:inline-block; width: 110px; margin-bottom: 30px;\r\n");
      out.write("height: 40px; line-height: 40px; text-align: center; background-color:#f3b8da; border-radius: 20px;\r\n");
      out.write("color:#000; position: relative; cursor: pointer; }\r\n");
      out.write("\r\n");
      out.write(".tab_con_wrap .tab_con_box { position: relative; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img { display: flex; width: 500px; height: 400px; position: absolute; z-index: 990; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img1 { display: flex; position: absolute; z-index: 999;  width: 100px; height: 105px;\r\n");
      out.write("margin-top: 70px; margin-left: 380px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img2 { display: flex; position: absolute; z-index: 999; width: 100px; height: 65px;\r\n");
      out.write("margin-top: 162px; margin-left: 380px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img3 { display: flex; position: absolute; z-index: 999;  width: 162px; height: 107px;\r\n");
      out.write("margin-top: 22px; margin-left: 92px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img4 { display: flex; position: absolute; z-index: 999;  width: 60px; height: 115px;\r\n");
      out.write("margin-top: 35px; margin-left: 375px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img5 { display: flex; position: absolute; z-index: 999;  width: 105px; height: 135px;\r\n");
      out.write("margin-top: 255px; margin-left: 392px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img6 { display: flex; position: absolute; z-index: 999;  width: 107px; height: 115px;\r\n");
      out.write("margin-top: 207px; margin-left: 310px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img7 { display: flex; position: absolute; z-index: 999;  width: 120px; height: 85px;\r\n");
      out.write("margin-top: 140px; margin-left: 267px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img8 { display: flex; position: absolute; z-index: 999;  width: 130px; height: 100px;\r\n");
      out.write("margin-top: -2px; margin-left: 267px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img9 { display: flex; position: absolute; z-index: 999;  width: 120px; height: 120px;\r\n");
      out.write("margin-top: 185px; margin-left: 370px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img10 { display: flex; position: absolute; z-index: 999;  width: 120px; height: 115px;\r\n");
      out.write("margin-top: 60px; margin-left: 270px; }\r\n");
      out.write(".tab_con_wrap .tab_con_box #img11 { display: flex; position: absolute; z-index: 999;  width: 210px; height: 180px;\r\n");
      out.write("margin-top: 128px; margin-left: 100px; }\r\n");
      out.write("\r\n");
      out.write(".tab_con_wrap .tab_con_box #img12 { display: flex; position: absolute; z-index: 999;  width: 145px; height: 105px;\r\n");
      out.write("margin-top: 293px; margin-left: 280px; }\r\n");
      out.write("\r\n");
      out.write(".tab_con_wrap .tab_con_box #img13 { display: flex; position: absolute; z-index: 999; width: 185px; height: 120px;\r\n");
      out.write("margin-top: 198px; }\r\n");
      out.write("\r\n");
      out.write("#ra1:checked ~ .btn_box label[for=\"ra1\"] { background-color: #DFB996; }\r\n");
      out.write("#ra2:checked ~ .btn_box label[for=\"ra2\"] { background-color: #DFB996; }\r\n");
      out.write("#ra3:checked ~ .btn_box label[for=\"ra3\"] { background-color: #DFB996; }\r\n");
      out.write("#ra4:checked ~ .btn_box label[for=\"ra4\"] { background-color: #DFB996; }\r\n");
      out.write("#ra5:checked ~ .btn_box label[for=\"ra5\"] { background-color: #DFB996; }\r\n");
      out.write("#ra6:checked ~ .btn_box label[for=\"ra6\"] { background-color: #DFB996; }\r\n");
      out.write("#ra7:checked ~ .btn_box label[for=\"ra7\"] { background-color: #DFB996; }\r\n");
      out.write("#ra8:checked ~ .btn_box label[for=\"ra8\"] { background-color: #DFB996; }\r\n");
      out.write("#ra9:checked ~ .btn_box label[for=\"ra9\"] { background-color: #DFB996; }\r\n");
      out.write("#ra10:checked ~ .btn_box label[for=\"ra10\"] { background-color: #DFB996; }\r\n");
      out.write("#ra11:checked ~ .btn_box label[for=\"ra11\"] { background-color: #DFB996; }\r\n");
      out.write("#ra12:checked ~ .btn_box label[for=\"ra12\"] { background-color: #DFB996; }\r\n");
      out.write("#ra13:checked ~ .btn_box label[for=\"ra13\"] { background-color: #DFB996; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f2_reused = false;
      try {
        _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f2.setParent(null);
        // /header.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f2.setVar("path0");
        // /header.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f2.setValue(request.getContextPath() );
        int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
        if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
        _jspx_th_c_005fset_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
      }
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f3_reused = false;
      try {
        _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f3.setParent(null);
        // /head.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f3.setVar("ipath");
        // /head.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f3.setValue(request.getContextPath() );
        int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
        if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
        _jspx_th_c_005fset_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
      }
      out.write("    \r\n");
      out.write("<!--  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.2.1.min.js\"></script>-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" />\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"subject\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("<meta property=\"og:type\" content=\"website\" />\r\n");
      out.write("<meta property=\"og:description\" content=\"\" />\r\n");
      out.write("<meta property=\"og:image\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("<meta property=\"og:url\" content=\"http://localhost:8091\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/fonts.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/normalize2.css\">\r\n");
      out.write("<meta name=\"subject\" content=\"강화 소개(GangHwa Intro)\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"강화, 맛집, 숙박, 쇼핑, 체험, 명소, 전시관, 박물관, 여행, 축제\" />\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/favicon.png\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ipath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/favicon.png\" />\r\n");
      out.write("<meta property=\"og:title\" content=\"gangHwa\" />\r\n");
      out.write("<meta property=\"og:description\" content=\"강화, 맛집, 숙박, 쇼핑, 체험, 명소, 전시관, 박물관, 여행, 축제\" />");
      out.write("\r\n");
      out.write("<header  id=\"hd\" class=\"clr-fix\">\r\n");
      out.write("	<div class=\"hd_wrap\">\r\n");
      out.write("            <div class=\"wrap clr-fix\">\r\n");
      out.write("                <nav id=\"gnb3\">\r\n");
      out.write("                    <ul class=\"menu\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"/teampro01\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/logo.png\" alt=\"로고\" id=\"logo\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/section.jsp\" class=\"dp1\" id=\"menu1\">강화소개</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/section.jsp\" class=\"dp2\" id=\"sub\">일반현황/행정구역</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/history.jsp\" class=\"dp2\" id=\"sub\">유래와 연혁</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/special.jsp\" class=\"dp2\" id=\"sub\">특산물/특산품</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/culture/library.jsp\" class=\"dp1\" id=\"menu2\">강화문화</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/culture/library.jsp\" class=\"dp2\" id=\"sub\">도서관</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/culture/museum.jsp\" class=\"dp2\" id=\"sub\">박물관</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/culture/gallery.jsp\" class=\"dp2\" id=\"sub\">전시관</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/travel/history1.jsp\" class=\"dp1\" id=\"menu3\">강화여행</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/travel/history1.jsp\" class=\"dp2\" id=\"sub\">명소</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/travel/jindallae5.jsp\" class=\"dp2\" id=\"sub\">축제</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/travel/farmersmarket8.jsp\" class=\"dp2\" id=\"sub\">체험여행</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/facility/food.jsp\" class=\"dp1\" id=\"menu4\">강화생활</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/facility/food.jsp\" class=\"dp2\" id=\"sub\">음식점</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/facility/hotel.jsp\" class=\"dp2\" id=\"sub\">숙박시설</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/facility/shop.jsp\" class=\"dp2\" id=\"sub\">쇼핑</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/traffic/traffic.jsp\" class=\"dp1\" id=\"menu5\">강화정보</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/traffic/traffic.jsp\" class=\"dp2\" id=\"sub\">교통정보</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/traffic/parking.jsp\" class=\"dp2\" id=\"sub\">공영주차장</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/traffic/come.jsp\" class=\"dp2\" id=\"sub\">오시는 길</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/NoticeList.do\" class=\"dp1\" id=\"menu6\">강화소통</a>\r\n");
      out.write("                            <ul class=\"sub\">\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/NoticeList.do\" class=\"dp2\" id=\"sub\">공지사항</a></li>\r\n");
      out.write("								<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/GetQnaList.do\" class=\"dp2\" id=\"sub\">건의사항</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("	<main id=\"contents\" class=\"clr-fix\">\r\n");
      out.write("        <div class=\"wrap clr-fix\">\r\n");
      out.write("            <div class=\"contents_wrap\">\r\n");
      out.write("                <aside id=\"left1\">\r\n");
      out.write("                    <nav id=\"lnb\">\r\n");
      out.write("                        <ul class=\"menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"dp1\">강화소개</a>\r\n");
      out.write("                                <ul class=\"sub\">\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/section.jsp\" class=\"dp2\" style=\"background-color: #f3b8da;\">일반현황/행정구역</a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/history.jsp\" class=\"dp2\">유래와연혁 </a></li>\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/special.jsp\" class=\"dp2\">특산물/특산품</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </aside>\r\n");
      out.write("                <div class=\"contents\">\r\n");
      out.write("                    <div class=\"breadcrumb\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"/teampro01\">HOME</a><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/section.jsp\">강화소개</a><span style=\"color:deeppink\">일반현황/행정구역</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h2 class=\"title\">일반현황/행정구역</h2>\r\n");
      out.write("                    <div class=\"wrap\">\r\n");
      out.write("                        <h3>1. 일반현황</h3>\r\n");
      out.write("                        <div class=\"box_img\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/general.jpg\" id=\"intro_img1\" alt=\"intro1\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <h3>2. 행정구역</h3>\r\n");
      out.write("                        <nav id=\"tab2\">\r\n");
      out.write("                            <div class=\"tb_wrap\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra1\" checked>\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra2\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra3\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra4\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra5\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra6\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra7\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra8\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra9\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra10\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra11\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra12\">\r\n");
      out.write("                                <input type=\"radio\" class=\"ra_item\" name=\"tb_ra2\" id=\"ra13\">\r\n");
      out.write("                                <div class=\"btn_box\">\r\n");
      out.write("                                    <label for=\"ra1\" class=\"ra_btn\">강화읍</label>\r\n");
      out.write("                                    <label for=\"ra2\" class=\"ra_btn\">선원면</label>\r\n");
      out.write("                                    <label for=\"ra3\" class=\"ra_btn\">교동면</label>\r\n");
      out.write("                                    <label for=\"ra4\" class=\"ra_btn\">송해면</label>\r\n");
      out.write("                                    <label for=\"ra5\" class=\"ra_btn\">길상면</label>\r\n");
      out.write("                                    <label for=\"ra6\" class=\"ra_btn\">양도면</label>\r\n");
      out.write("                                    <label for=\"ra7\" class=\"ra_btn\">내가면</label>\r\n");
      out.write("                                    <label for=\"ra8\" class=\"ra_btn\">양사면</label>\r\n");
      out.write("                                    <label for=\"ra9\" class=\"ra_btn\">불은면</label>\r\n");
      out.write("                                    <label for=\"ra10\" class=\"ra_btn\">하점면</label>\r\n");
      out.write("                                    <label for=\"ra11\" class=\"ra_btn\">삼산면</label>\r\n");
      out.write("                                    <label for=\"ra12\" class=\"ra_btn\">화도면</label>\r\n");
      out.write("                                    <label for=\"ra13\" class=\"ra_btn\">서도면</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"tab_con_wrap\">\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box1\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section1.png\" alt=\"section1\" id=\"img1\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box2\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section2.png\" alt=\"section2\" id=\"img2\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box3\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section3.png\" alt=\"section3\" id=\"img3\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box4\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section4.png\" alt=\"section4\" id=\"img4\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box5\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section5.png\" alt=\"section5\" id=\"img5\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box6\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section6.png\" alt=\"section6\" id=\"img6\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box7\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section7.png\" alt=\"section7\" id=\"img7\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box8\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section8.png\" alt=\"section8\" id=\"img8\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box9\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section9.png\" alt=\"section9\" id=\"img9\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box10\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section10.png\" alt=\"section10\" id=\"img10\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box11\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section11.png\" alt=\"section11\" id=\"img11\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box12\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section12.png\" alt=\"section12\" id=\"img12\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tab_con_box\" id=\"tab_con_box13\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section.jpg\" alt=\"section\" id=\"img\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/section13.png\" alt=\"section13\" id=\"img13\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<footer id=\"ft\" class=\"clr-fix\">\r\n");
      out.write("        <div class=\"ft_wrap\">\r\n");
      out.write("            <nav id=\"fnb\">\r\n");
      out.write("                <ul class=\"fl\">\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/term.jsp\">회원약관</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/policy.jsp\">개인정보처리방침</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/traffic/come.jsp\">찾아오시는길</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"loc\" style=\"margin-left:1200px;\">\r\n");
      out.write("                    <select name=\"sel\" id=\"sel\" onchange=\"locate()\">\r\n");
      out.write("                        <option value=\"\">유관기관</option>\r\n");
      out.write("                        <option value=\"https://www.ganghwa.go.kr/open_content/tour/\">강화군 문화관광</option>\r\n");
      out.write("                        <option value=\"https://hwagaejungwon.ganghwa.go.kr/\">화개정원</option>\r\n");
      out.write("                        <option value=\"https://www.ganghwa.go.kr/open_content/museum/\">강화 박물관</option>\r\n");
      out.write("                        <option value=\"http://www.ganghwapension.kr/\">강화 민박</option>\r\n");
      out.write("                        <option value=\"https://blog.naver.com/ktourtop10\">대한민국 테마여행 10선</option>\r\n");
      out.write("                        <option value=\"https://www.ghss.or.kr/\">강화군시설관리공단</option>\r\n");
      out.write("                        <option value=\"https://korean.visitkorea.or.kr/main/main.do\">대한민국구석구석</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"copy\">\r\n");
      out.write("                    <div class=\"addr\">[23037] 인천광역시 강화군 강화읍 강화대로 394</div>\r\n");
      out.write("                    <div class=\"tel\">TEL. 032-930-3114 FAX. 032-930-3660</div>\r\n");
      out.write("                    <div class=\"copyright\">COPYRIGHT(C) 2015 GANGHWA. ALL RIGHTS RESERVED.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div> \r\n");
      out.write("	<script>\r\n");
      out.write("		function locate(){\r\n");
      out.write("			var sel = document.getElementById(\"sel\");\r\n");
      out.write("			if(sel.value!=\"\"){\r\n");
      out.write("				window.open(sel.value);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /header.jsp(62,32) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sid }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/login.jsp\" class=\"dp2\" id=\"sub\">로그인</a></li>\r\n");
          out.write("								<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/join1.jsp\" class=\"dp2\" id=\"sub\">회원가입</a></li>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /header.jsp(66,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/LogOut.do\" onclick=\"log_out()\" class=\"dp2\" id=\"sub\">로그아웃</a></li>\r\n");
          out.write("								    ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("								    ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /header.jsp(68,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sid != 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/EditMember.do?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"dp2\" id=\"sub\">회원정보</a></li>\r\n");
          out.write("								    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /header.jsp(71,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sid == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							        <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/index.jsp\" class=\"dp2\" id=\"sub\">시스템관리자</a></li>\r\n");
          out.write("								    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
